import type { Metadata } from "next";
import { Sora, JetBrains_Mono } from "next/font/google";
import ConditionalHeader from "@/components/header/conditional-header";
import "./globals.css";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-x-hidden">
      <body
        className={`${sora.variable} ${jetbrainsMono.variable} antialiased transition-colors duration-300 min-h-screen overflow-x-hidden`}
      >
        <ConditionalHeader />
        {children}
      </body>
    </html>
  );
}
